### PR TITLE
Added Binary Search Tree, traversal methods of Binary tree

### LINKED ISSUE #1: Add common/generic algorithms to the Algorithms folder
Add to the algorithms folder some common/generic algorithms.
(Also add testcases for the given problems)

### PR DESCRIPTION
**Pull request by kailash360**
# Description

I have added the codes for implementation of different methods of a Binary Search Tree, and the different types of traversals in a Binary Tree.

Fixes #1 

## Type of change

- [x] New Update (Change which adds functionality or implements a new piece of code)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by 4molybdenum2** [comment]
Can you squash these changes into one commit? You can check up on rebasing it at https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by kailash360** [comment]
I have squashed the commits, sir

**Comment by 4molybdenum2** [comment]
I think you need to force push the commits otherwise you can see that there are currently 4 commits

**Comment by kailash360** [comment]
Sir, the local repo is up-to-date with the remote and the previous commits are persisting. If you say, I can close this PR create another one with a different branch, having a single commit.

**Comment by 4molybdenum2** [comment]
> Sir, the local repo is up-to-date with the remote and the previous commits are persisting. If you say, I can close this PR create another one with a different branch, having a single commit.

Yea that would be good. 😄

**Pull request closed without merging**
