### PR TITLE
Selction Sort and Insertion Sort

### PR DESCRIPTION
**Pull request by AmanPachori**
Hi @4molybdenum2 sir I have added the code Insertion sort and Selection sort

### CODE REVIEW

**Comment by 4molybdenum2** [comment]
Can you make this a generic function rather than a static array (take input from user) ?

**Comment by AmanPachori** [comment]
Yes sir I will update It

**Comment by AmanPachori** [comment]
@4molybdenum2  sir I have updated it

**Comment by AmanPachori** [comment]
@4molybdenum2 sir I have make the updated PR

**Comment by 4molybdenum2** [comment]
Ok looks good

**Comment by AmanPachori** [comment]
@4molybdenum2 sir I have query that can I add question of codeforces or codechef in this repo

**Pull request merged**
