### PR TITLE
Added implementation for AVL tree

### PR DESCRIPTION
**Pull request by SaahilSabu**
insertion and deletion for avl tree

### CODE REVIEW

**Comment by SaahilSabu** [comment]
will this be counted towards hacktober fest contribution?

**Comment by 4molybdenum2** [comment]
> will this be counted towards hacktober fest contribution?

I would suggest you do not open source just for the sake of a "title" , just do it freely for the community😄. But yes I will add the hacktoberfest-accepted label to this PR. 
Also pls change the title of the PR to something more definitive like "Added implementation for AVL tree".

**Comment by SaahilSabu** [comment]
sure sir

**Review by 4molybdenum2 — APPROVED** [review]
Looks good

**Comment by SaahilSabu** [comment]
kind reminder to add the hacktober fest label
ty :)

**Pull request merged**
